### ISSUE TITLE
Using <Validate> element inside <FormControl> causes <Select> label to bug

### ISSUE THREAD

**Issue by LucusWebsites** [kbrueckner/mui-validate#11]
Using \<Validate> element inside \<FormControl> causes \<Select> label to bug:

https://user-images.githubusercontent.com/3696955/165238628-2d0a0c57-29d7-46ed-8389-6fb8b79c121b.mp4

```jsx
<FormControl fullWidth>
    <InputLabel 
        required 
        id="desiredRealisationDateLabel"
    >
        {t('inputs.desiredRealisationDate')}
    </InputLabel>
    <Validate 
        name="desiredRealisationDate" 
        inputType="select"
        required={[true, t('validation.isRequiredMessage')]}
    > // <<<<<<<<< this element causes the Mui /<InputLabel> to stop working :(
        <Select
            value={userInput.desiredRealisationDate}
            required
            fullWidth
            name="desiredRealisationDate"
            labelId="desiredRealisationDateLabel"
            label={t('inputs.desiredRealisationDate')}
            onChange={handleSelectInputChange}
        >
            {desiredRealisationList.map((desiredRealisation) => {
                return desiredRealisationYearList.map((year) => {
                    return <MenuItem value={`${desiredRealisation}[${year}]`}>{t(`desiredRealisationDate.${desiredRealisation}`, { year })}</MenuItem>
                })
            })}
            <MenuItem value="other">{t('inputs.desiredRealisationDateUnknown')}</MenuItem>
        </Select>
    </Validate>
</FormControl>
```

Wrapping the \<Validate> Element around the \<FormControl> element fixes the label issue, but then validation is always false:

```jsx
<Validate 
    name="desiredRealisationDate" 
    inputType="select"
    required={[true, t('validation.isRequiredMessage')]}
>
    <FormControl fullWidth>
        <InputLabel
            required
            id="desiredRealisationDateLabel"
        >
            {t('inputs.desiredRealisationDate')}
        </InputLabel>
        ...
    </FormControl>
</Validate>

**Comment by kbrueckner** [comment]
This needs to be looked into. Will get back to you on that...

**Comment by kbrueckner** [comment]
I am having a hard time reproducing the issue which I can clearly see in the video.
What mui-validate version are you on and what version of material ui?

**Comment by LucusWebsites** [comment]
- "@mui/material": "5.4.4"
- "mui-validate": "0.1.0"

**Comment by eyevanovich** [comment]
I'm seeing the same thing here FWIW. I'd be more than happy to help debug this.

**Comment by eyevanovich** [comment]
To clarify, I'm seeing this behavior when wrapping a <FilledInput> within a <FormControl>. It does work if I wrap <FormControl> with <Validate>.
```javascript
            <FormControl fullWidth sx={{ m: 1 }} variant="filled">
              <InputLabel htmlFor="token-setting">Token</InputLabel>
              <Validate
                name="token"
                required={[
                  true,
                  'input required',
                ]}
              >
                <FilledInput
                  id="token-setting"
                  placeholder="Your token..."
                  size="small"
                  type={settings.showToken ? 'text' : 'password'}
                  value={settings.token}
                  onChange={handleChange('token')}
                  endAdornment={
                    <InputAdornment position="end">
                      <IconButton
                        aria-label="toggle password visibility"
                        onClick={handleClickShowPassword}
                        onMouseDown={handleMouseDownPassword}
                        edge="end"
                      >
                        {settings.showToken ? (
                          <VisibilityOff />
                        ) : (
                          <Visibility />
                        )}
                      </IconButton>
                    </InputAdornment>
                  }
                />
              </Validate>
            </FormControl>
```

**Comment by kbrueckner** [comment]
Thanks a lot also @eyevanovich - might get back to you later for debug help.

The reported problem goes back to the fact that the input elements are wrapped into a FormControl with an InputLabel as a sibling. The validation framework creates its own FormControl structure and therefore is not aware of the existing ones. If possible until the implementation for a solution, could you skip the outer FormControl for now?
I am aware of that the control is needed for selects - unfortunately I don't have an adhoc workaround for that.

**Comment by kbrueckner** [comment]
Guys, would you help me to test the fix?
I released a release candidate which can be installed via:
```
npm i mui-validate@0.2.1-rc.1
```

Please let me know if that solves the issue.

**Comment by LucusWebsites** [comment]
> Guys, would you help me to test the fix? I released a release candidate which can be installed via:
> 
> ```
> npm i mui-validate@0.2.1-rc.1
> ```
> 
> Please let me know if that solves the issue.

For me it does not resolve the issue, still having exactly the same problem.

**Comment by LucusWebsites** [comment]
> > Guys, would you help me to test the fix? I released a release candidate which can be installed via:
> > ```
> > npm i mui-validate@0.2.1-rc.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please let me know if that solves the issue.
> 
> For me it does not resolve the issue, still having exactly the same problem.

On further inspection, it does work now. It only doesn't work if I don't set the labelId attribute on the \<Select> element.

```jsx
<Select labelId="desiredRealisationDateLabel"
```

**Comment by kbrueckner** [comment]
Is that a good enough fix for you? I didn't try out if the label behaviour works without the labelId if you don't wrap it with a Validate component.

I am open for ideas on how to address the problem. We likely need an additional control parameter if we do not want to rely on labelId.

**Comment by LucusWebsites** [comment]
For me it is, thanks a lot for the fix!

**Comment by kbrueckner** [comment]
Thanks for continuously contributing by raising bugs and ideas. Please go ahead like this 😄
